<?php require_once("../../fb_validator.php"); ?>
<?php require_once("../../session_check.php"); ?>
<?php require_once("../../dbconnect.php"); ?>
<?php require_once("../../classes/order.php"); ?>
<?php require_once("../../classes/order_detail.php"); ?>
<?php require_once("../../classes/order_voucher.php"); ?>
<?php require_once("../../classes/voucher.php"); ?>
<?php require_once("../functions.php"); ?>
<?php require_once("getAll_data.php"); ?>

<?php 

/* ====================================================================== *
        GLOBAL VARS
 * ====================================================================== */       	

	$id_fb_user 	= $user['id'];
	$id_order 		= get_id_order($id_fb_user);
	$details 		= get_order_details($id_order);

	$POST 			= (array)json_decode(trim(file_get_contents('php://input')));

	if($id_order == '-1'){
		$output = array();
		$output['error'] = true;
		echo json_encode($output);
		exit();
	}

/* ====================================================================== *
        CLASSES
 * ====================================================================== */      

 	$order 				= new order();
	$order_detail 		= new order_detail();
	$order_voucher 		= new order_voucher();
	$voucher 			= new voucher(); 	

 /* ====================================================================== *
        DELETE ORDER DETAIL
 * ====================================================================== */       		

	$error = false;
	$conn->beginTransaction();

	$order_detail->set_id_order($id_order);
	$order_detail->set_id_order_detail($POST['id_order_detail']);
	if(!$order_detail->delete()){
		$error = true;
	}

	if(count($details)==1){
		
		// Delte order_vouchers

		if(!$order_voucher->delete_all_from_order($id_order)){
			$error = true;
		}

		// Delete leftover vouchers generated by this id_order

		if(!$voucher->delete_automatic_voucher($id_order)){
			$error = true;
		}

		// Delete order

		$order->set_id_order($id_order);
		if(!$order->delete()){
			$error = true;
		}
	}

	if($error){
      $conn->rollBack();
	}else{
      $conn->commit();
	}

/* ====================================================================== *
        JSON OUTPUT
 * ====================================================================== */       	

    $output = array();

    set_all($output);
    
    $output['error'] = $error;

	echo json_encode($output);

?>
