<html lang="en">
<head>

  	<?php require_once("../head.php"); ?>

	
	

</head>
<body>
	<div class="page-wrap"><div class="page-wrap-inner">

	<?php require_once("../menu.php"); ?>

	<div class="tabs-container">
	
	<br>
<br>
<br>


<h5>
<div><strong>TERMS &amp; CONDITIONS AND USER AGREEMENT</strong></div>
<div>Welcome to WWW.MIRACAS.com. WWW.MIRACAS.com provides their services to you subject to the terms and conditions given hereunder. By visiting WWW.MIRACAS.COM, you are accepting the practices described in this Privacy Notice, for use of the information provided by you on the site. Please do not access, use the site and provide information if you do not agree with this Notice. Please read them carefully. In addition, when you use any current or future MIRACAS.com service (e.g. Your Account/Profile, Gift Certificates, and Your Reminder Service, etc.) you will be subject to these guidelines and conditions for such service or business. These terms and conditions supersede all previous representations, understandings, or agreements and shall prevail notwithstanding any variance with any other terms of any order placed or service provided by MIRACAS. Accessing, browsing or otherwise using the site indicates your agreement to all the terms and conditions in this agreement. By using the shopping services of MIRACAS you agree to be bound by these terms and conditions. All products/services and information displayed on MIRACAS constitute an "invitation to offer". Your order for purchase constitutes your "offer" which shall be subject to the terms and conditions as listed below. MIRACAS reserves the right to accept or reject your offer.</div>
<div><strong>Applicable law</strong></div>
<div>This site is created and controlled by MIRACAS. The laws of India shall apply and courts in Mumbai alone shall have jurisdiction in respect of all the terms, conditions and disclaimers. MIRACAS reserves the right to make changes to the website and the terms, conditions and disclaimers at any time and without information to the customers/users of the services/website of MIRACAS.</div>
<div><strong>Definitions</strong></div>
<div>"Agreement" means the terms and conditions as detailed herein including all schedules, appendices, annexures, privacy policy, and will include the references to this agreement as amended, negated, supplemented, varied or replaced from time to time.</div>
<div>"MIRACAS.com'' / ''MIRACAS'' / ''website '' means the online shopping platform and the services provided by it, owned and operated by Miracas LifeStyle Pvt Ltd . which provides a venue / platform to the Users of MIRACAS to buy the products listed on WWW.MIRACAS.com.</div>
<div>"Vendor" / "seller" /''affiliates'' shall mean the person or any legal entity including but not limited to MIRACAS who offers for sale, sells the products on the MIRACAS platform / website.</div>
<div>"Product/Products" means and includes any goods / merchandise /products /services /offers /display items that are uploaded/ showcased/ displayed on MIRACAS and the related description, information, procedure, processes, warranties, delivery schedule, etc.</div>
<div>"Customer" / "buyer" shall mean the person or any legal entity who accepts the offer for sale on MIRACAS by placing an order for and purchases any product offered for sale on the platform of MIRACAS.</div>
<div>"User" / ''you" means and includes any person or an entity or any legal entity using or accessing the services provided on MIRACAS.</div>
<div>Electronic Communication</div>
<div>When you visit MIRACAS or send e-mails to us or give us your feedback, you are communicating with us electronically. You consent to receive communications from us electronically. We will communicate with you by e-mail or by posting notices on this website. You agree that all agreements, notices, disclosures and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing.</div>
<div>Disclaimer of Products</div>
<div>Information about prices, products, services and merchants is for informational purposes only. The product images are for representation only. We cannot guarantee that information is 100% correct. We will not be liable for any omissions, errors or delays or any kind of losses, injuries and damages arising from its display or use.</div>
<div>Disclaimer of warranties and limitation of liability</div>
<div>MIRACAS has made this service available to use as a matter of convenience. MIRACAS disclaims all warranties, express or implied, including, but not limited to, implied warranties of merchantability and fitness for a particular purpose. MIRACAS does not warrant that this site, its servers, or e-mail sent from MIRACAS are free of viruses or other harmful components. MIRACAS will not be liable for any damages of any kind arising from the use of this site, including, but not limited to direct, indirect, incidental, punitive, and consequential damages.</div>
<div>You can get a maximum of 50% discount on the products. Discount coupon and Reward points cannot be clubbed together for any discount. MIRACAS has the sole rights to add or remove reward points from any user's accounts at its own discretion.</div>
<div>The Service(s) of MIRACAS is provided on an "as is" basis without warranties of any kind, whether express or implied. MIRACAS does not represent or warrant maintaining the confidentiality of information; although MIRACAS&rsquo;s current practice is to ensure reasonable efforts to maintain such confidentiality. It is also clearly understood that all warranties, implied or express take place between the vendors and the User.</div>
<div>MIRACAS will not be responsible for any damage suffered by Users from use of the services on this site. This without limitation includes loss of revenue/data resulting from delays, non-deliveries, missed deliveries, or service interruptions as may occur because of any act / omission of the vendor. This disclaimer of liability also applies to any damages or injury caused by any failure of performance, error, omission, interruption, deletion, defect, delay in operation or transmission, computer virus, communication line failure, theft or destruction or unauthorized access to, alteration of, or use of record, whether for breach of contract, tortuous behavior, negligence, or under any other cause of action.</div>
<div>In no event shall WWW.MIRACAS.com be liable for any direct, indirect, punitive, incidental, special, consequential damages or any other damages resulting from: (a) the use or the inability to use the Services; (b) unauthorized access to or alteration of the user's transmissions or data; (c) any other matter relating to the services; including, without limitation, damages for loss of use, data or profits, arising out of or in any way connected with the use or performance of the Website or Service. Neither shall WWW.MIRACAS.com be responsible for the delay or inability to use the Website or related services, the provision of or failure to provide Services, or for any information, software, products, services and related graphics obtained through the Website, or otherwise arising out of the use of the website, whether based on contract, tort, negligence, strict liability or otherwise. Further, WWW.MIRACAS.com shall not be held responsible for non-availability of the Website during periodic maintenance operations or any unplanned suspension of access to the website that may occur due to technical reasons or for any reason beyond MIRACAS&rsquo;s control. The user understands and agrees that any material and/or data downloaded or otherwise obtained through the Website is done entirely at their own discretion and risk and they will be solely responsible for any damage to their computer systems or loss of data that results from the download of such material and/or data.</div>
<div>User agrees and acknowledges that User shall be solely responsible for User's conduct and that MIRACAS reserves the right to terminate your rights to use the service immediately, notwithstanding penal provisions under the Indian cyber laws or any other allied laws enacted by the government of India or any other statutory, legislative or regulatory authority authorized in this regard from time to time. In no event shall MIRACAS, its affiliates, employees, agents, consultants, contracted companies be liable for any direct, indirect, punitive, incidental, special or consequential damages or for any damages whatsoever including, without limitation, damages for loss of use, data or profits, arising out of or in any way connected with the use or performance of the MIRACAS sites/services for interrupted communications, delay, lost data or lost profits arising out of or in connection with this agreement.</div>
<div>MIRACAS therefore neither endorses nor offers any judgment or warranty and accepts no responsibility or liability for the authenticity/availability of any of the goods/services/or for any damage, loss or harm, direct or consequential or any violation of local or international laws that may be incurred by your visit and/or transaction/s on these sites.</div>
<div>MIRACAS shall not be liable for any delay / non-delivery of purchased goods by the vendors, trade organization/s, manufacturers / shop etc. (vendors), due to flood, fire, wars, acts of God or any cause that is beyond the control of MIRACAS.</div>
<div>Notwithstanding anything contained herein,. In no event shall MIRACAS, its directors, officials, representatives and employees be liable for any damages or claims relating to products sold through its various platforms. MIRACAS shall only provide replacement and/or manufacturer&rsquo;s warranty in case of MIRACAS branded goods which will vary from goods to goods.</div>
<div>All prices, unless indicated otherwise are in Indian Rupees. The availability of products is subject to change without prior notice at the sole discretion of MIRACAS and orders can be cancelled if the product goes out of stock. MIRACAS reserves the right to refuse or cancel any order placed for a product that is listed at an incorrect price which may be higher or lower than published. This shall be regardless of whether the order has been confirmed and/or payment been levied via credit card or cheque or otherwise. In the event the payment has been processed by MIRACAS the refund amount shall be credited to your credit card account and duly notified to you by email or sent by cheque.</div>
<div>In a credit/debit card transaction, you must use a credit /debit card that is issued in the name of the User. MIRACAS will not be liable for any credit/debit card fraud because of the card being used fraudulently. The liability to use a credit/debit card or a net banking transaction fraudulently will be on the User and the onus to 'prove otherwise' shall be exclusively on the User. Any request for cancellation of orders once duly placed on the site, shall not be entertained.</div>
<div>We as a merchant shall be under no liability whatsoever in respect of any loss or damage arising directly or indirectly out of the decline of authorization for any Transaction, on Account of the Cardholder having exceeded the preset limit mutually agreed by us with our acquiring bank from time to time.</div>
<div>In the event that a non-delivery occurs on account of a mistake by you (i.e. wrong name or address) any extra cost incurred by MIRACAS for re-delivery shall be claimed from the User placing the order.</div>
<div>MIRACAS reserves the right to charge a fee for any or such facilities or freight or handling charges or shipping charges or statutory taxes. MIRACAS and its affiliates reserve the right to cancel orders for the product in their sole discretion for any reason which can include but not limited to, the product being out of stock, or for any other reason without intimation to the User.</div>
<div><strong>Indemnification</strong>:</div>
<div>You agree to indemnify, defend and hold harmless MIRACAS.com from and against any and all losses, liabilities, claims, damages, costs and expenses (including legal fees and disbursements in connection therewith and interest chargeable thereon) asserted against or incurred by MIRACAS.com that arise out of, result from, or may be payable by virtue of, any breach or non-performance of any representation, warranty, covenant or agreement made or obligation to be performed by you pursuant to these Terms.</div>
<div>Trademark</div>
<div>The logo / image of MIRACAS on the home page of the website &amp; other pages and as used in the communication to the User is registered by MIRACAS and cannot be used or communicated or distributed without the specific and written permission of MIRACAS.</div>
<div>License and Site Access</div>
<div>MIRACAS grants you a limited license to access and make personal use of this site and not to download (other than page caching) or modify it, or any portion of it, except in case MIRACAS gives consent for the same. This license does not include any resale or commercial use of this site or its contents; any collection and use of any product listings, descriptions, or prices; any derivative use of this site or its contents; any downloading or copying of account information for the benefit of another merchant; or any use of data mining, robots, or similar data gathering and extraction tools. This site or any portion of this site may not be reproduced, duplicated, copied, sold, resold, visited, or otherwise exploited for any commercial purpose without express written consent of MIRACAS. You may not frame or use framing techniques to enclose any trademark, logo, or other proprietary information (including images, text, page layout, or form) of MIRACAS.com and our affiliates without express written consent. You may not use any meta tags or any other "hidden text" and MIRACAS's name or trademarks without the express written consent of MIRACAS. Any unauthorized use terminates the permission or license granted by MIRACAS. You are granted a limited, revocable, and nonexclusive right to create a hyperlink to the home page of MIRACAS as long as the link does not portray MIRACAS, its affiliates, or their products or services in a false, misleading, derogatory, or otherwise offensive matter or having a right to ownership of the same in any form. You may not use any MIRACAS logo or other proprietary graphic or trademark as part of the link without express written permission.</div>
<div><strong>Your Account</strong></div>
<div>If you use this site, you are responsible for maintaining the confidentiality of your account and password and for restricting access to your computer, and also you agree to accept responsibility for all activities that occur under your account or password. MIRACAS and its affiliates reserve the right to refuse service, terminate accounts, remove or edit content, or cancel orders in their sole discretion.</div>
<div><strong>Cancellation of order</strong></div>
<div>WWW.MIRACAS.com reserves the right to cancel any order without any explanation for doing so, under situation where WWW.MIRACAS.com is not able to meet the requirement of the order placed or order so placed/cancelled does not comply with the WWW.MIRACAS.com policy or for any other reason. However, WWW.MIRACAS.com will ensure that any communication of cancellation of an order, so cancelled, is intimated within appropriate time to the concerned person and any applicable refund, will be made in reasonable time.</div>
<div><strong>Reviews, Comments, Communications, and other Content</strong></div>
<div>Visitors may post reviews, comments, and other content; and submit suggestions, ideas, comments, questions, or other information, so long as the content is not illegal, obscene, threatening, defamatory, invasive of privacy, infringing on intellectual property rights, or otherwise injurious to third parties or objectionable and does not consist of or contain software viruses, political campaigning, commercial solicitation, chain letters, mass mailings, or any form of "spam." You may not use a false e-mail address, impersonate any person or entity, or otherwise mislead as to the origin of a card or other content. MIRACAS reserves the right (but not the obligation) to remove or edit such content, but does not regularly review posted content.</div>
<div>If you do post content or submit material, and unless we indicate otherwise, you grant MIRACAS and its affiliates a nonexclusive, royalty-free, perpetual, irrevocable, and fully sub-licensable right to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, and display such content throughout the world in any media. You grant MIRACAS and its affiliates and sub-licenses the right to use the name that you submit in connection with such content, if they choose. You represent and warrant that you own or otherwise control all of the rights to the content that you post; that the content is accurate; that use of the content you supply does not violate this policy and will not cause injury to any person or entity; and that you will indemnify MIRACAS or its affiliates for all claims resulting from content you supply. MIRACAS has the right but not the obligation to monitor and edit or remove any activity or content. MIRACAS takes no responsibility and assumes no liability for any content posted by you or any third party.</div>
<div>Suspension due to Non-Compliance with Agreement</div>
<div>Notwithstanding other legal remedies that may be available to MIRACAS, MIRACAS may in its sole discretion limit user activity by immediately removing user listing either temporarily or indefinitely or suspend or terminate user membership, and/or refuse to provide user with access to the site if:</div>
<div>The user is in breach any of the terms and conditions of this agreement and/or the terms and conditions of usage of MIRACAS.</div>
<div>The user has provided wrong, inaccurate, incomplete or incorrect information.</div>
<div>Your actions may cause any harm, damage or loss to the other Users or MIRACAS.</div>
<div>Illegal and/or unauthorized use of the service, including unauthorized framing of or linking to the MIRACAS site will be investigated, and appropriate legal action will be taken, including without limitation, civil, criminal and injunctive redress.</div>
<div>Risk of Loss</div>
<div>All items purchased from MIRACAS are made pursuant to a shipment contract. This means that the risk of loss and title for such items pass to you upon the delivery to the carrier by the vendor/merchant/affiliate/manufacturer or MIRACAS.</div>
<div>Product Description</div>
<div>MIRACAS and its affiliates attempt to be as accurate as possible. However, MIRACAS does not warrant that product descriptions or other content or prices/amounts of this site is accurate, complete, reliable, current, or error-free. If a product offered by MIRACAS itself is not as described, your sole remedy is to return it in unused condition.</div>
<div><strong>Pricing</strong></div>
<div>Except where noted otherwise, the Selling Price/MRP/MOP/List Price displayed for products on our website represents the full retail price listed on the product itself, suggested /offered by the manufacturer or supplier or one of our merchants/affiliates, or estimated in accordance with standard industry practice; or the estimated retail value for a comparably featured item offered elsewhere. The Selling Price/MRP/MOP/List Price is a comparative price estimate and may or may not represent the prevailing price in every area on any particular day. For certain items that are offered as a set/pack/combo/arrangement, the Selling Price/List Price may represent ''open-stock'' prices, which mean the aggregate of the manufacturer's estimated or suggested retail price for each of the items included in the set/pack/combo/arrangement.</div>
<div>Material Submitted by Users</div>
<div>Certain elements of the site will contain material submitted by users. MIRACAS accepts no responsibility for the content, accuracy, conformity to applicable laws of such material.</div>
<div>Data Protection</div>
<div>MIRACAS may send information and offers of products and services to you from time to time. For further details relating to our policy relating to such offer please refer to our privacy policy.</div>
<div>Force Majeure</div>
<div>MIRACAS shall have no liability to you for any interruption or delay in access to the Site irrespective of the cause.</div>
<div>Entire Agreement</div>
<div>These Terms of Service constitute the entire agreement between the parties with respect to the subject matter hereof and supersedes and replaces all prior or contemporaneous understandings or agreements, written or oral, regarding such subject matter. The clauses as above shall survive the termination or expiry of this agreement.</div>
 </h5>



﻿
</div>
</div>
</div> <!-- End tabs-container -->
	

	<?php require_once("../footer.php"); ?>

</body>

</html>